// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAaiNo8s4vw-natzF4E9viksMSFUyT9js',
    appId: '1:303643756807:web:fdc775850afd42ef27dda2',
    messagingSenderId: '303643756807',
    projectId: 'we-chat-ac9b7',
    authDomain: 'we-chat-ac9b7.firebaseapp.com',
    storageBucket: 'we-chat-ac9b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoAHn46QS8b-WM88hDWms_zxtC7MuOMfk',
    appId: '1:303643756807:android:ffa9038ce51342ae27dda2',
    messagingSenderId: '303643756807',
    projectId: 'we-chat-ac9b7',
    storageBucket: 'we-chat-ac9b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBjuoK6gliVlZelf4tRGEL7DG3eIIePM',
    appId: '1:303643756807:ios:509abf558e20938327dda2',
    messagingSenderId: '303643756807',
    projectId: 'we-chat-ac9b7',
    storageBucket: 'we-chat-ac9b7.appspot.com',
    androidClientId: '303643756807-36plj1jrbpqe8htkboe546tdnpr2np4v.apps.googleusercontent.com',
    iosClientId: '303643756807-uli9ne98umit13jtq16rr2n2k0jedset.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSBjuoK6gliVlZelf4tRGEL7DG3eIIePM',
    appId: '1:303643756807:ios:509abf558e20938327dda2',
    messagingSenderId: '303643756807',
    projectId: 'we-chat-ac9b7',
    storageBucket: 'we-chat-ac9b7.appspot.com',
    androidClientId: '303643756807-36plj1jrbpqe8htkboe546tdnpr2np4v.apps.googleusercontent.com',
    iosClientId: '303643756807-uli9ne98umit13jtq16rr2n2k0jedset.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );
}
